import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b2d414",
        "inverse-surface": "#2e3131",
        "on-error-container": "#93000a",
        "primary-container": "#0e2f22",
        "on-tertiary-fixed": "#171e00",
        "primary-fixed": "#c7ebd7",
        "on-surface": "#191c1c",
        "error": "#ba1a1a",
        "on-tertiary-container": "#819b00",
        "surface-container-highest": "#e1e3e2",
        "tertiary": "#121700",
        "outline": "#727974",
        "surface-container": "#eceeed",
        "surface-variant": "#e1e3e2",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#92f7c3",
        "inverse-primary": "#abcfbb",
        "on-tertiary": "#ffffff",
        "background": "#f8faf9",
        "surface-container-high": "#e6e9e8",
        "on-primary-container": "#769886",
        "on-primary-fixed-variant": "#2d4d3f",
        "primary-fixed-dim": "#abcfbb",
        "tertiary-fixed": "#cdf139",
        "tertiary-container": "#242d00",
        "on-secondary-fixed-variant": "#005235",
        "on-background": "#191c1c",
        "surface-bright": "#f8faf9",
        "inverse-on-surface": "#eff1f0",
        "outline-variant": "#c1c8c2",
        "on-error": "#ffffff",
        "on-secondary-container": "#00734d",
        "surface": "#f8faf9",
        "on-primary-fixed": "#002115",
        "on-secondary-fixed": "#002113",
        "surface-dim": "#d8dada",
        "surface-tint": "#456555",
        "secondary": "#006c48",
        "on-primary": "#ffffff",
        "on-surface-variant": "#414844",
        "secondary-fixed-dim": "#75daa8",
        "secondary-container": "#92f7c3",
        "primary": "#00190f",
        "surface-container-low": "#f2f4f3",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#3e4c00"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
    },
  },
  plugins: [],
};
export default config;
